# Generated by Django 3.2.18 on 2023-05-04 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_post_voetballer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voetballer',
            old_name='text',
            new_name='naam_vereniging',
        ),
        migrations.RenameField(
            model_name='voetballer',
            old_name='title',
            new_name='naam_voetballer',
        ),
    ]
